"""Fixed some column fields

Revision ID: a3048f9f443f
Revises: b063e3ddcbaa
Create Date: 2023-11-04 14:34:51.058248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a3048f9f443f"
down_revision: Union[str, None] = "b063e3ddcbaa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("bookings", "room_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("bookings", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "bookings",
        "total_cost",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=False,
    )
    op.alter_column(
        "bookings", "total_days", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("bookings", "total_days", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "bookings",
        "total_cost",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=True,
    )
    op.alter_column("bookings", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("bookings", "room_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
